[build]
  publish = "./"  # Если папка `frontend` загружена как отдельный проект
  command = ""    # Поскольку это статический проект, билд-команда не нужна

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 