[build]
  publish = "./" # Указывает, что публиковать из текущей папки
  command = ""   # Статический сайт, поэтому команда сборки не требуется

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
